return {
  "echasnovski/mini.icons",
  opts = {
    default = {},
    directory = {},
    extension = {
      db = { glyph = "", hl = "MiniIconsBlue" },
      sqlite = { glyph = "", hl = "MiniIconsBlue" },
      fish = { glyph = "󰈺", hl = "MiniIconsGreen" },
    },
    file = {
      -- ["blink-cmp.lua"] = { glyph = "󱐀", hl = "MiniIconsOrange" },
      -- ["snippets.lua"] = { glyph = "", hl = "MiniIconsOrange" },
      ["README.md"] = { glyph = "󰂺", hl = "MiniIconsWhite" },
      ["autocmds.lua"] = { glyph = "", hl = "MiniIconsOrange" },
      ["build.zig"] = { glyph = "", hl = "MiniIconsYellow" },
      ["core.lua"] = { glyph = "", hl = "MiniIconsOrange" },
      ["deno.json"] = { glyph = "󰏓", hl = "MiniIconsOrange" },
      ["deno.lock"] = { glyph = "", hl = "MiniIconsBlue" },
      ["disable.lua"] = { glyph = "", hl = "MiniIconsRed" },
      ["keymaps.lua"] = { glyph = "󰘳", hl = "MiniIconsOrange" },
      ["lazy.lua"] = { glyph = "󰒲", hl = "MiniIconsPurple" },
      ["mini-icons.lua"] = { glyph = "", hl = "MiniIconsPurple" },
      ["nerdy.lua"] = { glyph = "", hl = "MiniIconsOrange" },
      ["options.lua"] = { glyph = "", hl = "MiniIconsOrange" },
      ["package.json"] = { glyph = "󰏓", hl = "MiniIconsOrange" },
      ["root.zig"] = { glyph = "", hl = "MiniIconsYellow" },
      ["terminal-colors.json"] = { glyph = "", hl = "MiniIconsBlue" },
      ["terminal-cursor-controls.json"] = { glyph = "", hl = "MiniIconsBlue" },
      ["terminal-general-ascii.json"] = { glyph = "", hl = "MiniIconsBlue" },
      ["terminal-modes.json"] = { glyph = "", hl = "MiniIconsBlue" },
      ["tmux-navigator.lua"] = { glyph = "", hl = "MiniIconsGreen" },
      ["yazi.toml"] = { glyph = "󰇥", hl = "MiniIconsYellow" },
    },

    filetype = {},
    lsp = {},
    os = {},
  },
}
