return {
  -- {
  --   "supermaven-inc/supermaven-nvim",
  --   config = function()
  --     require("supermaven-nvim").setup({
  --       keymaps = {
  --         accept_suggestion = "<Tab>",
  --         clear_suggestion = "<A-c>",
  --         accept_word = "<A-w>",
  --       },
  --       ignore_filetypes = { cpp = true }, -- or { "cpp", }
  --       color = {
  --         suggestion_color = "#ffffff",
  --         cterm = 244,
  --       },
  --       log_level = "info", -- set to "off" to disable logging completely
  --       disable_inline_completion = false, -- disables inline completion for use with cmp
  --       disable_keymaps = false, -- disables built in keymaps for more manual control
  --     })
  --   end,
  -- },
  --
  -- -- Disabling Tab
  --
  -- {
  --   "L3MON4D3/LuaSnip",
  --   keys = {
  --     { "<tab>", false, mode = { "i", "s" } },
  --     { "<s-tab>", false, mode = { "i", "s" } },
  --   },
  -- },
  -- {
  --   "hrsh7th/nvim-cmp",
  --   keys = {
  --     { "<tab>", false, mode = { "i", "s" } },
  --     { "<s-tab>", false, mode = { "i", "s" } },
  --   },
  -- },
}
