return {
  "echasnovski/mini.icons",
  opts = {
    default = {},
    directory = {},
    extension = {
      db = { glyph = "", hl = "MiniIconsBlue" },
      sqlite = { glyph = "", hl = "MiniIconsBlue" },
    },
    file = {
      ["deno.json"] = { glyph = "󰏓", hl = "MiniIconsOrange" },
      ["deno.lock"] = { glyph = "", hl = "MiniIconsBlue" },
      ["README.md"] = { glyph = "", hl = "MiniIconsCyan" },
      ["lazy.lua"] = { glyph = "󰒲", hl = "MiniIconsPurple" },
      ["autocmds.lua"] = { glyph = "", hl = "MiniIconsOrange" },
      ["options.lua"] = { glyph = "", hl = "MiniIconsOrange" },
      ["keymaps.lua"] = { glyph = "󰘳", hl = "MiniIconsOrange" },
      ["snippets.lua"] = { glyph = "", hl = "MiniIconsOrange" },
      ["mini_icons.lua"] = { glyph = "", hl = "MiniIconsPurple" },
      ["disable.lua"] = { glyph = "", hl = "MiniIconsRed" },
      ["tmux_navigator.lua"] = { glyph = "", hl = "MiniIconsGreen" },
      ["render_markdown_custom.lua"] = { glyph = "󰽛", hl = "MiniIconsAzure" },
      ["yazi_nvim.lua"] = { glyph = "󰇥", hl = "MiniIconsYellow" },
      ["yazi.toml"] = { glyph = "󰇥", hl = "MiniIconsYellow" },
    },
    filetype = {},
    lsp = {},
    os = {},
  },
}
